ans=[
#U5 T1#
"let alone",
"It turns out that",
"Thanks to",
"give away",
"lose marbles",
"smell a rat",
"watch over",
"What's even better",
"tedious",
"typcoon",
"agile",
"indignantly",
"confront",
"affection",
"persuade",
"contently",
#U5 T2#
"at one's fingertips",
"drift apart",
"take over",
"distract from",
"take a toll on",
"result from",
"get on",
"radically",
"hinder",
"unprecedented",
"concern",
"incessant",
"accomplish",
"exterminate",
"outlandish",
#U6 T1#
"teem with",
"made up of",
"bring about",
"the tip of the iceberg",
"give a boost",
"without its risk",
"serve no purpose",
"marine",
"vibrantly",
"starve",
"trigger",
"vulnerable",
"restore",
"species",
"lament",
#U6 T2#
"entangled in",
"every corner of the planet",
"wean from",
"remain to be seen",
"make an effort to",
"branch out into",
"derive from",
"complicated",
"equivalent",
"drift",
"rapidly",
"reliance",
"repurpose",
"permeate",
"gravity",
#U7 T1
'keep up',
'keep from',
'take action',
'resort to',
'correspond with',
'societal',
'chronically',
'desperate',
'resolve',
'rectify',
'disparity',
'pressing',
'alleviate',
'overwhelming',
'concrete',
#U7 T2
'beyond control',
'pose a risk',
'pose risks',
'hold firm to',
'equate to',
'hold water',
'be comprised of',
'appalled',
'circumstance',
'grave',
'combat',
'maginalized',
'mingle','
'exacerbate',
'ignorance',
'dismiss'
]
score=len(ans)
for i in ans:
    num=ans.index(i)+1
    inp=input(f'{num}. ')
    if inp != i:
        print('Wrong')
        score-=1
print(f'{score}/len(ans))